version: '3'

services:
  recipe-mysql:
    image: 'nazerwow/recipe-mysql'
    container_name: recipeapp
    ports:
           - "3308:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=ironhack-user1
           - MYSQL_DATABASE=recipeapp
           - MYSQL_USER=ironhack-user1
           - MYSQL_PASSWORD=ironhack-user1
           - MYSQL_ROOT_HOST=%
    volumes:
           - ./recipeapp:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    # restart: always
  discovery-service:
    image: 'nazerwow/discovery-service'
    ports:
           - "8761:8761"
    depends_on:
           - "db"
    # restart: always
  api-gateway:
    image: 'nazerwow/api-gateway'
    ports:
           - "8080:8080"
    depends_on:
           - "recipe-mysql"
           - "discovery-service"
    environment:
      - eureka.client.service-url.defaultZone = http://discovery-service:8761/eureka
      - eureka.instance.prefer-ip-address=true
    # restart: always
  recipe-service:
    image: 'nazerwow/recipe-service'
    ports:
           - "8100:8100"
    links:
           - "recipe-mysql"
    depends_on:
           - "recipe-mysql"
           - "discovery-service"
           - "api-gateway"
    environment:
      - spring.datasource.url=jdbc:mysql://recipe-mysql:3306/recipeapp?createDatabaseIfNotExist=true
      - eureka.client.service-url.defaultZone = http://discovery-service:8761/eureka
      - eureka.instance.prefer-ip-address=true
    restart: always
  user-service:
    image: 'nazerwow/user-service'
    ports:
           - "7000"
    links:
           - "recipe-mysql"
    depends_on:
           - "recipe-mysql"
           - "discovery-service"
           - "api-gateway"
           - "recipe-service"
    environment:
      - spring.datasource.url=jdbc:mysql://recipe-mysql:3306/recipeapp?createDatabaseIfNotExist=true
      - eureka.client.service-url.defaultZone = http://discovery-service:8761/eureka
      - eureka.instance.prefer-ip-address=true
    # restart: always
  favourites-service:
    image: 'nazerwow/favourites-service'
    ports:
           - "8300"
    links:
           - "recipe-mysql"
    depends_on:
           - "recipe-mysql"
           - "discovery-service"
           - "api-gateway"
           - "recipe-service"
           - "user-service"
    environment:
      - spring.datasource.url=jdbc:mysql://recipe-mysql:3306/recipeapp?createDatabaseIfNotExist=true
      - eureka.client.service-url.defaultZone = http://discovery-service:8761/eureka
      - eureka.instance.prefer-ip-address=true
    # restart: always
  rating-service:
    image: 'nazerwow/rating-service'
    ports:
           - "8400"
    links:
           - "recipe-mysql"
    depends_on:
           - "recipe-mysql"
           - "discovery-service"
           - "api-gateway"
           - "recipe-service"
           - "user-service"
    environment:
      - spring.datasource.url=jdbc:mysql://recipe-mysql:3306/recipeapp?createDatabaseIfNotExist=true
      - eureka.client.service-url.defaultZone = http://discovery-service:8761/eureka
      - eureka.instance.prefer-ip-address=true
    # restart: always
  review-service:
    image: 'nazerwow/review-service'
    ports:
           - "8600"
    links:
           - "recipe-mysql"
    depends_on:
           - "recipe-mysql"
           - "discovery-service"
           - "api-gateway"
    environment:
      - spring.datasource.url=jdbc:mysql://recipe-mysql:3306/recipeapp?createDatabaseIfNotExist=true
      - eureka.client.service-url.defaultZone = http://discovery-service:8761/eureka
      - eureka.instance.prefer-ip-address=true
    # restart: always