version: '2'

services:
  recipe-mysql:
    image: 'nazerwow/recipe-mysql'
    cpu_shares: 100
    mem_limit: 262144000
    ports:
           - "3308:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=ironhack-user1
           - MYSQL_DATABASE=recipeapp
           - MYSQL_USER=ironhack-user1
           - MYSQL_PASSWORD=ironhack-user1
           - MYSQL_ROOT_HOST=%
    logging:
      driver: awslogs
      options:
        awslogs-group: recipebox
        awslogs-region: eu-west-2
        awslogs-stream-prefix: web
  discovery-service:
    image: 'nazerwow/discovery-service'
    cpu_shares: 100
    mem_limit: 262144000
    ports:
           - "8761"
    depends_on:
           - "db"
    logging:
      driver: awslogs
      options:
        awslogs-group: recipebox
        awslogs-region: eu-west-2
  api-gateway:
    image: 'nazerwow/api-gateway'
    cpu_shares: 100
    mem_limit: 262144000
    container_name: api-gateway
    ports:
           - "8080:8080"
    depends_on:
           - "recipe-mysql"
           - "discovery-service"
    logging:
      driver: awslogs
      options:
        awslogs-group: recipebox
        awslogs-region: eu-west-2
        awslogs-stream-prefix: web
    environment:
      - eureka.client.service-url.defaultZone = http://discovery-service:8761/eureka
      - eureka.instance.prefer-ip-address=true
  recipe-service:
    image: 'nazerwow/recipe-service'
    cpu_shares: 100
    mem_limit: 262144000
    ports:
           - "8100"
    links:
           - "recipe-mysql"
    depends_on:
           - "recipe-mysql"
           - "discovery-service"
           - "api-gateway"
    logging:
      driver: awslogs
      options:
        awslogs-group: recipebox
        awslogs-region: eu-west-2
        awslogs-stream-prefix: web
    environment:
      - spring.datasource.url=jdbc:mysql://recipe-mysql:3306/recipeapp?createDatabaseIfNotExist=true
      - eureka.client.service-url.defaultZone = http://discovery-service:8761/eureka
      - eureka.instance.prefer-ip-address=true
    restart: always
  user-service:
    image: 'nazerwow/user-service'
    cpu_shares: 100
    mem_limit: 262144000
    ports:
           - "7000"
    links:
           - "recipe-mysql"
    depends_on:
           - "recipe-mysql"
           - "discovery-service"
           - "api-gateway"
           - "recipe-service"
    environment:
      - spring.datasource.url=jdbc:mysql://recipe-mysql:3306/recipeapp?createDatabaseIfNotExist=true
      - eureka.client.service-url.defaultZone = http://discovery-service:8761/eureka
      - eureka.instance.prefer-ip-address=true
    logging:
      driver: awslogs
      options:
        awslogs-group: recipebox
        awslogs-region: eu-west-2
        awslogs-stream-prefix: web
  favourites-service:
    image: 'nazerwow/favourites-service'
    cpu_shares: 100
    mem_limit: 262144000
    ports:
           - "8300"
    links:
           - "recipe-mysql"
    depends_on:
           - "recipe-mysql"
           - "discovery-service"
           - "api-gateway"
           - "recipe-service"
           - "user-service"
    environment:
      - spring.datasource.url=jdbc:mysql://recipe-mysql:3306/recipeapp?createDatabaseIfNotExist=true
      - eureka.client.service-url.defaultZone = http://discovery-service:8761/eureka
      - eureka.instance.prefer-ip-address=true
    logging:
      driver: awslogs
      options:
        awslogs-group: recipebox
        awslogs-region: eu-west-2
        awslogs-stream-prefix: web
  rating-service:
    image: 'nazerwow/rating-service'
    cpu_shares: 100
    mem_limit: 262144000
    ports:
           - "8400"
    links:
           - "recipe-mysql"
    depends_on:
           - "recipe-mysql"
           - "discovery-service"
           - "api-gateway"
           - "recipe-service"
           - "user-service"
    environment:
      - spring.datasource.url=jdbc:mysql://recipe-mysql:3306/recipeapp?createDatabaseIfNotExist=true
      - eureka.client.service-url.defaultZone = http://discovery-service:8761/eureka
      - eureka.instance.prefer-ip-address=true
    logging:
      driver: awslogs
      options:
        awslogs-group: recipebox
        awslogs-region: eu-west-2
        awslogs-stream-prefix: web
  review-service:
    image: 'nazerwow/review-service'
    cpu_shares: 100
    mem_limit: 262144000
    ports:
           - "8600"
    links:
           - "recipe-mysql"
    depends_on:
           - "recipe-mysql"
           - "discovery-service"
           - "api-gateway"
    environment:
      - spring.datasource.url=jdbc:mysql://recipe-mysql:3306/recipeapp?createDatabaseIfNotExist=true
      - eureka.client.service-url.defaultZone = http://discovery-service:8761/eureka
      - eureka.instance.prefer-ip-address=true
    logging:
      driver: awslogs
      options:
        awslogs-group: recipebox
        awslogs-region: eu-west-2
        awslogs-stream-prefix: web
  recipeapp-frontend:
    image: 'nazerwow/recipeapp-frontend'
    cpu_shares: 100
    mem_limit: 262144000
    ports:
           - "4200:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: recipebox
        awslogs-region: eu-west-2
        awslogs-stream-prefix: web